appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
travis:
  secure:
    BINSTAR_TOKEN: UWD/c1QVus5KnNuLkXBmn2jgP+8rwvwXAG6/Y9vkiYklvqqD3hnOyVrM2bUwm51DPm0NopWJSgR0Ew5+OknP8b+Ov/Rkf5nyO0B1AzLGBq5kPG1ojVrc0IZ6GCu2Nf3nmwD22KQ9Va0K5UxHCV1ykCG+b40Tc3+bhE4atcHKmIZ3uIdaAzQ3LGKJ8dyNFe0Pg58DF9LpnGGkTD9ppGTdTbkCl7Rhrr7BwS7Fhtp2s3u6lSfE67vh7JySD7CO25wHa65mrp0+9BsFOKiUh5f3AjAXak4VG0KmYyosht/Qb3cS3F9ObVxFbBjQrWBEhPes3V8Xq80IAW23+ATweRj83UFsG+L/4oonkQ9PBWph+DmZxY1aVcSCc20sy5bL6OJeV+M0Q0VrV+RKL3cXE9wJM83AL1jXRfHLnb07yURaSzSwSOf6n5EsRMjwc7GYp+zaQq/NIGDVlcN+9JBKqhb3QdXU1z3WsnF0V3YHw0/DN+JzNtO34zh45rReYywenYNEdYhS/mqmKBDxBKTi1EymgOuVXO5QmjD7wZVWp5KBHIJZa0iIBB6D8P6Hu0F2qlDNDNHOb1zLr+tYzYAgkhZRP5bZNXJfm1WRDQ4C7zSp6lczpj3PzUTZE3nEzHQpGXq1cRZc9yApMRm0Ie7WA8cNfEMcZEYPsroHQNq92CWYKbE=
conda_forge_output_validation: true
bot:
  automerge: true
